In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
tokenizer=Tokenizer()

In [3]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [4]:
tokenizer.fit_on_texts([faqs])

In [52]:
len(tokenizer.word_index)

282

In [6]:


input_sequences=[]

# printing sentences as sequence of number
for sentence in faqs.split("\n"):
   tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
   # Combining the sequences like if a sentence has [98,99,100] it gives [98,99],[98,99,100]
   for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])


In [7]:
input_sequences

[[93, 1],
 [93, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 68],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 5],
 [1, 12, 94, 5, 44],
 [1, 12, 94, 5, 44, 29],
 [1, 12, 94, 5, 44, 29, 95],
 [1, 12, 94, 5, 44, 29, 95, 30],
 [1, 12, 94, 5, 44, 29, 95, 30, 2],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6

In [8]:
max_length=max([len(x) for x in input_sequences])  #Calculating maximum length of a sentence

In [9]:
max_length

57

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequence=pad_sequences(input_sequences,maxlen=max_length,padding='pre')  #To make the length of all the sentences same

In [11]:
padded_input_sequence

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]])

In [12]:
x=padded_input_sequence[:,:-1]    #Except last column all are input sequences

In [13]:
y=padded_input_sequence[:,-1]

In [14]:
y

array([  1,  13,   7,   1,  12,  42,  15,  43,  53,  68,  13, 147, 148,
        12,  94,   5,  44,  29,  95,  30,   2,   8,   4,  26,  44,  69,
         6,  31,  70,  45,   7,   1,  71,  72,   6,   1,  12,  71,  72,
         6,   1,  12,   7,  54,  73,  32,   1,  71,  12,  42, 149,  70,
        54,  31,  55, 150,   7,   1,  96,   6,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  15,  43,  53, 156,  15,  43,  53,
        15, 159,  74, 160,  98,  99,  10, 163,   1, 164,  96,  76,  77,
       100,  33,  14, 165,  33,  43,  53,  68,  13, 166, 101,  74,  20,
       102,  19,   5,  78,   6,  21,  13, 102,  20, 101,  74, 167,  56,
        46,   5,  78,   6,  21, 168, 169,  22,   3, 104,   5, 105,  34,
         9,   3,  47,   5, 106,   6,   1,  34,  16,  35,  17,  56, 170,
        32, 107,  22,   2, 104,   5,  34,   2,  10, 171, 172,  20,  57,
         1, 106,  10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,
        45,  59,  45, 109, 177,   6,   1,  12,  77, 178,  58,  6

In [15]:
y.shape

(863,)

In [16]:
x.shape

(863, 56)

In [17]:
# Converting output to one hot encoding
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=283)

In [18]:
y.shape

(863, 283)

# Architecture

In [19]:
# Embedding layer-->LSTM--->Dense layer  Added embedding layer since there are many sparse vectors so converting the sparse vector to dense vector


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [75]:
model=Sequential()
model.add(Embedding(283,100,input_length=56))
model.add(LSTM(150))

model.add(Dense(283,activation='softmax'))



In [78]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.build(input_shape=(None, 56))


In [79]:

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ (None, 56, 100)             │          28,300 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_8 (LSTM)                        │ (None, 150)                 │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 283)                 │          42,733 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 221,633 (865.75 KB)

 Trainable params: 221,633 (865.75 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
import tensorflow as tf
print(tf.__version__)


2.17.0


In [29]:
print(model.built)

True


In [84]:
model.fit(x,y,epochs=100)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - accuracy: 0.9460 - loss: 0.1117
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 63ms/step - accuracy: 0.9547 - loss: 0.1094
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.9551 - loss: 0.1237
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - accuracy: 0.9529 - loss: 0.1097
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - accuracy: 0.9507 - loss: 0.1021
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy: 0.9547 - loss: 0.1102
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 66ms/step - accuracy: 0.9506 - loss: 0.1111
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - accuracy: 0.9582 - loss: 0.0959
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - accuracy: 0.9516 - loss: 0.1087
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - accuracy: 0.9501 - loss: 0.1088
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 0.9528 - loss: 0.1091
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step

In [85]:
import time
import numpy as np
from keras.preprocessing.sequence import pad_sequences

text = "mail"
for i in range(10):
    # Tokenize and pad input
    token_text = tokenizer.texts_to_sequences([text])[0]
    padded_token_input = pad_sequences([token_text], maxlen=max_length, padding='pre')

    # Predict next word probabilities
    prediction = model.predict(padded_token_input)
    print("Prediction vector:", prediction)

    # Get the index with the highest probability
    pos = np.argmax(prediction)
    print("Chosen position:", pos)

    # Find the word corresponding to the index
    word = tokenizer.index_word.get(pos, "")
    print("Chosen word:", word)

    # Check if the word was found
    if word:
        text += " " + word
        print("Updated text:", text)
    else:
        print("Word not found for position:", pos)
        break

    # Delay for visualization
    time.sleep(2)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Prediction vector: [[8.74083889e-06 1.15176418e-03 2.55364296e-03 3.40275801e-05
  4.66531892e-05 1.11161804e-04 3.06225884e-05 1.24730732e-05
  6.66084088e-05 7.17660878e-04 1.70118787e-04 2.85011483e-05
  6.53127383e-04 8.56483937e-04 2.98508792e-04 2.73262686e-03
  1.81012034e-01 6.08523469e-03 4.19112184e-04 5.12709084e-05
  3.99464136e-03 5.52505208e-03 3.57368226e-05 2.37150598e-05
  2.60891183e-03 1.01160188e-03 1.48390624e-04 1.40524033e-04
  1.64125900e-04 1.87443311e-05 4.46488884e-05 2.19964841e-03
  1.31169427e-03 6.77366770e-05 3.85638923e-05 4.90439907e-02
  2.76201899e-04 7.76323650e-05 2.48346420e-04 8.28138000e-05
  5.86067363e-05 1.75514913e-04 3.75199052e-05 8.73436034e-03
  4.04727319e-03 1.37108483e-03 1.66919315e-03 6.94896153e-06
  6.16369925e-06 3.43143865e-02 1.56605546e-03 2.84597132e-04
  5.15487802e-04 1.91934683e-04 1.54490292e-03 1.94037220e-05
  2.03688219e-02 4.98469672e-05 8.08682700e-04 2.45160959e-03
  1.39645854e

In [47]:
import numpy as np

In [86]:
model.predict(padded_token_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[4.48815535e-06, 2.21425594e-07, 7.16152787e-02, 2.52098631e-04,
        2.69349228e-04, 1.68197006e-02, 1.20553101e-04, 6.20902807e-04,
        2.47380952e-03, 3.25444201e-03, 1.86849385e-01, 6.80208723e-06,
        4.58364630e-05, 1.37827490e-04, 1.87591813e-05, 5.90375625e-03,
        3.92737138e-06, 3.71118149e-05, 1.61094868e-05, 4.57589340e-04,
        1.34688802e-03, 1.36563713e-05, 3.62376571e-02, 4.46351798e-04,
        8.07352408e-05, 6.35239267e-05, 5.45572315e-04, 3.43340973e-04,
        1.87571088e-04, 1.31155321e-05, 1.19099664e-02, 3.71354076e-06,
        5.06978948e-03, 3.74027266e-04, 5.04598429e-04, 1.40066689e-03,
        1.48368772e-05, 1.61542592e-03, 2.83933696e-06, 4.05182533e-07,
        9.42844736e-08, 2.07951828e-03, 1.79538663e-04, 1.05646288e-03,
        6.32088768e-06, 1.05428280e-05, 1.65307763e-04, 1.27091611e-04,
        3.06580091e-06, 3.63840445e-05, 8.77957518e-06, 3.37257688e-06,
        2.27384389e-05, 3.15397891e-04, 2.10884507e-04, 2.191174